{
 "title": "State Sync",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "metrics_source",
    "query": {
     "query": "label_values(node_process_start_time{}, metrics_source)"
    }
   },
   {
    "name": "chain_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\"}, chain_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, kubernetes_pod_name)"
    }
   },
   { "name": "role", "query": { "query": "label_values(role)" } },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "General Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Committed Version",
   "type": "graph",
   "description": "Version of the latest ledger info committed. Any synced transactions beyond this version will not be considered committed",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "version number" }
   ],
   "targets": [
    {
     "expr": "aptos_state_sync_version{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", type=\"committed\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Synced Version",
   "type": "graph",
   "description": "The version of the latest transaction synced",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "version number" }
   ],
   "targets": [
    {
     "expr": "aptos_state_sync_version{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", type=\"synced\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "graph",
   "description": "Epoch of local state",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aptos_state_sync_epoch{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Active Upstream Peers",
   "type": "graph",
   "description": "Number of peers that are currently active and upstream. They are the set of nodes a node can make sync requests to",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Num upstream peers" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role, network) (aptos_state_sync_active_upstream_peers{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} - {{network}} network"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  },
  {
   "title": "Failed Storage Read",
   "type": "graph",
   "description": "rate of storage read failures ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_storage_read_fail_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Failed Network Sends",
   "type": "graph",
   "description": "rate of number of times a aptosNet network send failed",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_requests_sent_total{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", result=\"fail\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) + rate(aptos_state_sync_responses_sent_total{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", result=\"fail\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Failed channel sends",
   "type": "graph",
   "description": "rate of number of times a channel send failed",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_failed_channel_sends_total{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} - {{type}}"
    }
   ]
  },
  {
   "title": "Commit Flow Failures",
   "type": "graph",
   "description": "rate of failures encountered in the commit flow across consensus, state sync, and mempool",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_commit_flow_fail_total{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} - {{component}}"
    }
   ]
  },
  {
   "title": "Reconfig Notification Failure",
   "type": "graph",
   "description": "rate of number of times a reconfig notification failed to happen",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_reconfig_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", result=\"fail\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Chunk Responses Received from Downstream",
   "type": "graph",
   "description": "rate of chunk responses received from a downstream peer ",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_responses_from_downstream_total{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} <- ({{network}}:{{peer}})"
    }
   ]
  },
  {
   "title": "Consensus Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true
  },
  {
   "title": "Msgs Received",
   "type": "graph",
   "description": "number of requests (e.g. commit, sync) received from consensus",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "msgs" }
   ],
   "targets": [
    {
     "expr": "aptos_state_sync_coordinator_msg_latency_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} - {{type}}"
    }
   ]
  },
  {
   "title": "Sync Requests Completed",
   "type": "graph",
   "description": "number of sync requests from consensus completed",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aptos_state_sync_sync_request_total{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", result=\"complete\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Failed Sync Requests",
   "type": "graph",
   "description": "rate of sync requests (from consensus) that did not succeed (e.g. failed, timed out)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_sync_request_total{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", result!=\"complete\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} - {{result}}"
    }
   ]
  },
  {
   "title": "Msgs Received",
   "type": "graph",
   "description": "number of requests (e.g. commit, sync) received from consensus",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "msg / s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_coordinator_msg_latency_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} - {{type}}"
    }
   ]
  },
  {
   "title": "Sync Requests Completed Rate",
   "type": "graph",
   "description": "number of sync requests from consensus completed",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "requests / s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_sync_request_total{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", result=\"complete\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Process Sync Msg Latency",
   "type": "graph",
   "description": "latency of processing sync msg from consensus",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_coordinator_msg_latency_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", type=\"sync\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(aptos_state_sync_coordinator_msg_latency_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", type=\"sync\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Consensus Commit Fail",
   "type": "graph",
   "description": "rate of number of times a commit msg from consensus failed to be processed",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_consensus_commit_fail{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Process Commit Msg Latency",
   "type": "graph",
   "description": "Latency of processing commit msg from consensus",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_coordinator_msg_latency_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", type=\"commit\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval]) / rate(aptos_state_sync_coordinator_msg_latency_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", type=\"commit\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Sync Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true
  },
  {
   "title": "Apply Chunk Success",
   "type": "graph",
   "description": "number of times a chunk was successfully applied to local state",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aptos_state_sync_apply_chunk_total{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", result=\"success\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} <- ({{network}}:{{sender}})"
    }
   ]
  },
  {
   "title": "Apply Chunk Failure",
   "type": "graph",
   "description": "number of times a received chunk failed to be applied to local state",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aptos_state_sync_apply_chunk_total{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", result=\"fail\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} <- ({{network}}:{{sender}})"
    }
   ]
  },
  {
   "title": "Target Version",
   "type": "graph",
   "description": "A version a node is trying to sync up to",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aptos_state_sync_version{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", type=\"target\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Apply Chunk Success Rate",
   "type": "graph",
   "description": "number of times a chunk was successfully applied to local state",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short", "label": "success / s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_apply_chunk_total{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", result=\"success\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} <- ({{network}}:{{sender}})"
    }
   ]
  },
  {
   "title": "Apply Chunk Failure Rate",
   "type": "graph",
   "description": "number of times a received chunk failed to be applied to local state",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
   "yaxes": [
    { "format": "short", "label": "failures / s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_apply_chunk_total{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", result=\"fail\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} <- ({{network}}:{{sender}})"
    }
   ]
  },
  {
   "title": "Transaction Replayed",
   "type": "graph",
   "description": "number of transactions state synchronizer has retrieved since last restart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aptos_state_sync_chunk_size_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} <- {{network}}:{{sender}}"
    }
   ]
  },
  {
   "title": "Chunk E2E Latency",
   "type": "graph",
   "description": "How long it took to sync a chunk, from requesting a chunk to fully processing and executing it",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_sync_progress_duration_s_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(aptos_state_sync_sync_progress_duration_s_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Chunk Size",
   "type": "graph",
   "description": "number of txns in a chunk",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "yaxes": [
    { "format": "short", "label": "# of transactions" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_chunk_size_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(aptos_state_sync_chunk_size_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} <- ({{network}}:{{sender}})"
    }
   ]
  },
  {
   "title": "Transaction Replayed Rate",
   "type": "graph",
   "description": "number of transactions state synchronizer has retrieved since last restart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
   "yaxes": [
    { "format": "short", "label": "replays / s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_chunk_size_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} <- {{network}}:{{sender}}"
    }
   ]
  },
  {
   "title": "Execute/Commit Chunk Latency",
   "type": "graph",
   "description": "time it takes to execute and commit a chunk (via executor proxy)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_execute_chunk_duration_s_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(aptos_state_sync_execute_chunk_duration_s_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Requests and Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "collapsed": true
  },
  {
   "title": "Requests Sent Rate",
   "type": "graph",
   "description": "rate of number of chunk requests sent",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short", "label": "requests / s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_requests_sent_total{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", result=\"success\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} -> ({{network}}:{{peer}})"
    }
   ]
  },
  {
   "title": "Chunk Response Received Rate",
   "type": "graph",
   "description": "rate of number of chunk responses received",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 93 },
   "yaxes": [
    { "format": "short", "label": "responses / s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_process_msg_latency_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", type=\"chunk_response\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} <- ({{network}}:{{sender}})"
    }
   ]
  },
  {
   "title": "Multicast Level",
   "type": "graph",
   "description": "number of networks the node is sending chunk requests to. =0 if the primary upstream network is healthy, else >0",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 93 },
   "yaxes": [
    { "format": "short", "label": "# of networks" }
   ],
   "targets": [
    {
     "expr": "aptos_state_sync_multicast_level{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  },
  {
   "title": "Process Chunk Request Success Rate",
   "type": "graph",
   "description": "rate of number of times a node successfully processed a chunk request",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short", "label": "requests / s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_process_chunk_request_total{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", result=\"success\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} <- ({{network}}:{{sender}})"
    }
   ]
  },
  {
   "title": "Process Chunk Request Failure Rate",
   "type": "graph",
   "description": "rate of number of times this node failed to process an incoming chunk request",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 101 },
   "yaxes": [
    { "format": "short", "label": "failures / s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_process_chunk_request_total{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", result=\"fail\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} <- ({{network}}:{{sender}})"
    }
   ]
  },
  {
   "title": "Average Chunk Response Process Latency",
   "type": "graph",
   "description": "time it takes to process a chunk response",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 101 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_process_msg_latency_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", type=\"chunk_response\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(aptos_state_sync_process_msg_latency_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", type=\"chunk_response\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} <- ({{network}}:{{sender}})"
    }
   ]
  },
  {
   "title": "Average Chunk Request Process Latency",
   "type": "graph",
   "description": "time it takes to process a chunk request",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_process_msg_latency_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", type=\"chunk_request\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(aptos_state_sync_process_msg_latency_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", type=\"chunk_request\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} <- ({{network}}:{{sender}})"
    }
   ]
  },
  {
   "title": "Subscription Delivery Rate",
   "type": "graph",
   "description": "rate of number of times a FN long-poll subscription was delivered (does not include times where the initial FN chunk request was immediately responded to)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 109 },
   "yaxes": [
    { "format": "short", "label": "deliveries / s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_subscription_delivery_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}} -> {{network}}:{{recipient}} - {{result}}"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 },
   "collapsed": true
  },
  {
   "title": "Sent Chunk Request Timeout Rate",
   "type": "graph",
   "description": "rate of times a node's sent chunk request timed out",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short", "label": "timeouts / s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_state_sync_timeout_total{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}:{{role}}"
    }
   ]
  }
 ]
}