{
 "title": "Storage Overview",
 "tags": [ "aptos-core" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "metrics_source",
    "query": {
     "query": "label_values(node_process_start_time{}, metrics_source)"
    }
   },
   {
    "name": "chain_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\"}, chain_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, kubernetes_pod_name)"
    }
   },
   { "name": "role", "query": { "query": "label_values(role)" } },
   { "name": "cf_name", "query": { "query": "label_values(cf_name)" } },
   {
    "name": "api_name",
    "query": {
     "query": "aptos_storage_api_latency_seconds_count"
    }
   },
   {
    "name": "backup_service_api_name",
    "query": {
     "query": "aptos_backup_service_latency_s_count"
    }
   },
   {
    "name": "timer_name",
    "query": {
     "query": "aptos_storage_other_timers_seconds_sum"
    }
   },
   { "name": "db_name", "query": { "query": "label_values(db_name)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "These are basic facts that can be useful for understanding what's happening on chain right now.\r\n\r\nFollow the sections below this to examine the three major focus areas of the storage system health.\r\n"
   }
  },
  {
   "title": "latest version, epoch, pruner versions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(aptos_storage_latest_transaction_version{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
     "legendFormat": "latest (synced) (max)"
    },
    {
     "expr": "max(aptos_storage_ledger_version{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
     "legendFormat": "committed (max)"
    },
    {
     "expr": "sort_desc(quantile by (pruner_name) (0.8, aptos_pruner_min_readable_version{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", pruner_name !=\"state_store\"}))",
     "legendFormat": "{{kubernetes_pod_name}} {{pruner_name}} pruned-till (p80)"
    },
    {
     "expr": "max(aptos_storage_next_block_epoch{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
     "legendFormat": "epoch (max)"
    }
   ]
  },
  {
   "title": "Transactions per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(irate(aptos_storage_latest_transaction_version{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m]) < 10000)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Transactions per save",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(irate(aptos_storage_latest_transaction_version{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m]) / on (kubernetes_pod_name, kubernetes_pod_name) irate(aptos_storage_api_latency_seconds_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", api_name=\"save_transactions\", role=~\"$role\", result=\"Ok\"}[1m]) < 10000)",
     "legendFormat": "{{kubernetes_pod_name}} "
    }
   ]
  },
  {
   "title": "Free Space / Sizes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
     "options": {
      "content": "We expect nodes to have more than 200GB free space all the time.\r\n\r\nIdentify outliers on the left and filter by peer name to see it's specific values on the other panels. Otherwise you are seeing average values."
     }
    },
    {
     "title": "latest total number of state items (p80)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "quantile(0.8, aptos_storage_state_items{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "(max) latest total state KV size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(aptos_storage_total_state_bytes{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "quantile(0.8, aptos_storage_total_state_bytes{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"} / aptos_storage_state_items)",
       "legendFormat": "per item"
      }
     ]
    },
    {
     "title": "1 hour state item growth (p80)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(quantile(0.8, aptos_storage_state_items{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})[1h])",
       "legendFormat": "items created in 1 hour"
      },
      { "expression": "2000000000 / $B", "type": "math" }
     ]
    },
    {
     "title": "1 hour state bytes growth (p80)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(quantile(0.8, aptos_storage_total_state_bytes{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})[1h])",
       "legendFormat": "state bytes created in the past hour"
      },
      { "expression": "1000000000000 / $B", "type": "math" }
     ]
    },
    {
     "title": "DB size by column family",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(avg by(cf_name)(avg_over_time(aptos_rocksdb_properties{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", property_name=\"aptos_rocksdb_total-sst-files-size\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[5m])))",
       "legendFormat": "TOTAL"
      },
      {
       "expr": "sort_desc(avg by(cf_name)(avg_over_time(aptos_rocksdb_properties{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", property_name=\"aptos_rocksdb_total-sst-files-size\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[5m])))",
       "legendFormat": "{{cf_name}}"
      }
     ]
    },
    {
     "title": "Ledger on disk sizes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(avg by(cf_name)(avg_over_time(aptos_rocksdb_properties{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", property_name=\"aptos_rocksdb_total-sst-files-size\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", cf_name=~\"transaction|event_accumulator|transaction_info|transaction_accumulator|event|transaction_by_hash|event_by_version|event_by_key|transaction_by_account|version_data|ledger_info|epoch_by_version|db_metadata|default\"}[5m])))",
       "legendFormat": "TOTAL"
      },
      { "expression": "$B / $C", "type": "math" },
      {
       "expr": "sort_desc(avg by(cf_name)(avg_over_time(aptos_rocksdb_properties{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", property_name=\"aptos_rocksdb_total-sst-files-size\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", cf_name=~\"transaction|event_accumulator|transaction_info|transaction_accumulator|event|transaction_by_hash|event_by_version|event_by_key|transaction_by_account|version_data|ledger_info|epoch_by_version|db_metadata|default\"}[5m])))",
       "legendFormat": "{{cf_name}}"
      }
     ]
    },
    {
     "title": "JMT on disk sizes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(avg by(cf_name)(avg_over_time(aptos_rocksdb_properties{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", property_name=\"aptos_rocksdb_total-sst-files-size\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", cf_name=~\"jellyfish_merkle_node|stale_node_index|stale_node_index_cross_epoch\"}[5m])))",
       "legendFormat": "TOTAL"
      },
      { "expression": "$B / $C", "type": "math" },
      {
       "expr": "sort_desc(avg by(cf_name)(avg_over_time(aptos_rocksdb_properties{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", property_name=\"aptos_rocksdb_total-sst-files-size\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", cf_name=~\"jellyfish_merkle_node|stale_node_index|stale_node_index_cross_epoch\"}[5m])))",
       "legendFormat": "{{cf_name}}"
      }
     ]
    },
    {
     "title": "State KV on disk sizes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(avg by(cf_name)(avg_over_time(aptos_rocksdb_properties{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", property_name=\"aptos_rocksdb_total-sst-files-size\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", cf_name=~\"state_value|write_set|stale_state_value_index\"}[5m])))",
       "legendFormat": "TOTAL"
      },
      { "expression": "$B / $D", "type": "math" },
      {
       "expr": "sort_desc(avg by(cf_name)(avg_over_time(aptos_rocksdb_properties{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", property_name=\"aptos_rocksdb_total-sst-files-size\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", cf_name=~\"state_value|write_set|stale_state_value_index\"}[5m])))",
       "legendFormat": "{{cf_name}}"
      }
     ]
    },
    {
     "title": "Free Disk Space",
     "type": "timeseries",
     "description": "Free disk space on the DB volume. Less than a few GiBs, it's a problem.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sort_desc(node_disk_available_space{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",  persistentvolumeclaim!~\".*prometheus.*\", type!=\"rootfs\", name!=\"overlay\", role=~\"$role\"})",
       "legendFormat": "{{kubernetes_pod_name}} {{type}} {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "options": {
      "content": "# Are we the bottleneck?\n\nThese graphs show how much time was spent in execution/commit stages.\n**If any of them is close to 1 second, that pipeline stage might be the current bottlenect in the system.**\nTo further understand the bottleneck, go to \"Storage Details\" dashboard.\n\nNote: These numbers are measured on the block_executor/chunk_executor side. It's not a bad idea to cross check these numbers with the numbers measured in consensus/state_sync side. If the numbers don't match, it might be an indication of a scheduling issue.\n\nOther things to look at if these stages are slow:\n- IOPS\n- CPU usage\n- API latencies\n- Number of txns per save (block size and/or chunk size)"
     }
    },
    {
     "title": "Time Spent in Execution per Second (consensus)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(aptos_executor_execute_block_seconds_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m])\r\n",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Time Spent in Commit per Second (consensus)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(aptos_executor_commit_blocks_seconds_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Time Spent in Execution/Apply per Second (state sync)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sort_desc(rate(aptos_executor_apply_chunk_seconds_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m]))",
       "legendFormat": "{{kubernetes_pod_name}} apply"
      },
      {
       "expr": "sort_desc(rate(aptos_executor_execute_chunk_seconds_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m]))",
       "legendFormat": "{{kubernetes_pod_name}} execute"
      }
     ]
    },
    {
     "title": "Time Spent in Commit per Second (state sync)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(aptos_executor_commit_chunk_seconds_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
     "options": {
      "content": "# Disk IO\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
     }
    },
    {
     "title": "# of disk IO in progress",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "rate(node_linux_disk_io_in_progress{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}} {{name}}"
      }
     ]
    },
    {
     "title": "CPU time waiting for IO",
     "type": "timeseries",
     "description": "100% = 1vCPU",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sort_desc(irate(node_linux_system_cpu_usage{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\", state=\"iowait_ms\"}[1m]) / 1000)",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "IOPS (Linux Only)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sort_desc(rate(node_linux_disk_num_reads{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1m]))",
       "legendFormat": "{{kubernetes_pod_name}} {{name}} read"
      },
      {
       "expr": "sort_desc(rate(node_linux_disk_num_writes{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1m]))",
       "legendFormat": "{{kubernetes_pod_name}} {{name}} write"
      }
     ]
    },
    {
     "title": "Time spent in disk IO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(node_linux_disk_total_io_time_ms{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1m]) / 1000",
       "legendFormat": "{{kubernetes_pod_name}} {{name}}"
      }
     ]
    },
    {
     "title": "SchemaDB get() latency",
     "type": "timeseries",
     "description": "This reflects the IO performance of the underlying device.\n\nExpect single or double digits of microseconds.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name) (irate(aptos_schemadb_get_latency_seconds_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m])) / sum by (kubernetes_pod_name) (irate(aptos_schemadb_get_latency_seconds_count[1m]))",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "latest version, epoch, pruner versions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sort_desc(aptos_storage_latest_transaction_version{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
       "legendFormat": "{{kubernetes_pod_name}} ver"
      },
      {
       "expr": "sort_desc(aptos_storage_next_block_epoch{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
       "legendFormat": "{{kubernetes_pod_name}} epoch"
      },
      {
       "expr": "aptos_storage_ledger_version{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "ver"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 23 },
     "options": {
      "content": "Errors can be due to either internal or external reasons.\n\nTBD"
     }
    },
    {
     "title": "# of API Calls",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name) (irate(aptos_storage_api_latency_seconds_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API Success Rate",
     "type": "timeseries",
     "description": "Successes / (Successes + Errors)",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name) (irate(aptos_storage_api_latency_seconds_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", result=\"Ok\"}[1m])) / sum by (kubernetes_pod_name) (irate(aptos_storage_api_latency_seconds_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m]))",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "# of Errors",
     "type": "timeseries",
     "description": "This panel should show \"No data\" when there is no error.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name) (irate(aptos_storage_api_latency_seconds_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", result=\"Err\"}[1m]))",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  }
 ]
}